settings:
  cycle_detection:
    enabled: false
  project_id: "weewar"
  color_logs: true
  color_scheme: "dark"
  prefix_logs: true
  prefix_max_length: 15
  default_debounce_delay: 2s

rules:
  # Go Backend Development & Testing
  - name: "betests"
    watch:
      - action: "include"
        patterns:
          - "web/server/*.go"
      - action: "exclude"
        patterns:
          - "**/*.log"
          - "**/*.log"
          - "web/**/*"
          - "web"
      - action: "include"
        patterns:
          - "lib/**/*.go"
          - "cmd/**/*.go"
          - "services/**/*.go"
    commands:
      - "echo '🔧 Running WeeWar Tests...'"
      - "make test"
  - name: "backend"
    color: "blue"
    lro: true
    watch:
      - action: "include"
        patterns:
          - "web/server/*.go"
          - "lib/**/*.go"
          - "cmd/**/*.go"
          - "services/**/*.go"
          - "go.mod"
          - "go.sum"
      - action: "exclude"
        patterns:
          - "**/*.log"
          - "**/*.log"
          - "web/**/*"
          - "web"
    commands:
      - "echo '🔧 Building WeeWar Binary...'"
      - "make wasm"
      - "make binlocal"
      - "echo '✅ Backend build and tests complete'"
      - "pkill weewar || true"
      - "./bin/weewar serve"

  # Frontend Development & Testing
  - name: "frontend"
    skip_run_on_init: true
    color: "green"
    workdir: "./web"
    watch:
      - action: "exclude"
        patterns:
          - "gen/**"
          - "**/*.log"
          - "node_modules/**"
          - "dist/**"
          - "test-results/**"
          - "playwright-report/**"
          - "node_modules"
      - action: "include"
        patterns:
          - "**/*.ts"
          - "**/*.css"
          - "**/*.html"
          - "**/*.spec.ts"
          - "**/*.test.ts"
          - "package.json"
          - "vite.config.ts"
          - "tsconfig.json"
    commands:
      - "echo '⚡ Building frontend...'"
      - "npm run build"

  - name: "fetests"
    workdir: "./web"
    watch:
      - action: "exclude"
        patterns:
          - "frontend/gen/**"
          - "**/*.log"
          - "node_modules/**"
          - "dist/**"
          - "test-results/**"
          - "playwright-report/**"
          - "node_modules"
      - action: "include"
        patterns:
          - "**/*.ts"
          - "**/*.css"
          - "**/*.html"
          - "**/*.spec.ts"
          - "**/*.test.ts"
          - "package.json"
          - "vite.config.ts"
          - "tsconfig.json"
    commands:
      - "echo '🧪 Running frontend tests...'"
      # - "npm run test"
      - "npm run test:e2e"

  # Protocol Buffers (affects both Go and Web)
  - name: "protobuf"
    color: "magenta"
    skip_run_on_init: true
    watch:
      - action: "include"
        patterns:
          - "protos/**/*.proto"
          - "buf.yaml"
          - "buf.gen.yaml"
    commands:
      - "echo '📦 Regenerating Protocol Buffers...'"
      - "rm -Rf gen"
      - "buf generate"
      - "echo '✅ Protobuf generation complete'"
