runtime: go124

env_variables:
  # Production environment (triggers loading configs/.env)
  WEEWAR_ENV: production
  WEEWAR_BASE_URL: https://weewar.appspot.com
  # Backend storage configuration
  # Options: local, pg, gae
  WORLDS_SERVICE_BE: gae
  GAMES_SERVICE_BE: gae
  FILESTORE_BE: local
  # GAE_PROJECT is automatically set by App Engine (GOOGLE_CLOUD_PROJECT)
  # GAE_NAMESPACE can be set for multi-tenancy (optional)

handlers:
# Static files (JS, CSS, images, WASM)
- url: /static
  static_dir: web/static

# All other routes handled by Go app
- url: /.*
  script: auto
